# Base configs
baseurl: "https://kunaljagyasi.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Kunal Jagyasi"
subtitle: "See the world through my eyes!"
author: "Kunal Jagyasi"
header:
 title: "Photography"
 subtitle: "by Kunal Jagyasi"
footer:
 name: "Hey there, my name is Kunal"
 bio: "I am a Professional Photographer from Nagpur with experience and photography and cinematography."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/kunaljagyasi311/"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/kunal-jagyasi-1b4537211/"
  #github: "https://www.github.com/rampatra"
